/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define LED_ORANGE  13
#define LED_RED  14
#define BTN1 1
#define BTN0 0
// Table 10. Register boundary addresses
// RCC base and register
#define RCC_BASE_ADDR       (0x40023800)
#define RCC_AHB1ENR_OFFSET  (0x30)
#define RCC_AHB1ENR         (*((volatile uint32_t *)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET)))

// GPIOA base and registers
#define GPIOA_BASE_ADDR     (0x40020000)
#define GPIOA_MODER         (*((volatile uint32_t *)(GPIOA_BASE_ADDR + 0x00)))
#define GPIOA_PUPDR         (*((volatile uint32_t *)(GPIOA_BASE_ADDR + 0x0C)))
#define GPIOA_IDR           (*((volatile uint32_t *)(GPIOA_BASE_ADDR + 0x10)))

// GPIOD base and registers
#define GPIOD_BASE_ADDR     (0x40020C00)
#define GPIOD_MODER         (*((volatile uint32_t *)(GPIOD_BASE_ADDR + 0x00)))
#define GPIOD_OTYPER        (*((volatile uint32_t *)(GPIOD_BASE_ADDR + 0x04)))
#define GPIOD_PUPDR         (*((volatile uint32_t *)(GPIOD_BASE_ADDR + 0x0C)))
#define GPIOD_ODR           (*((volatile uint32_t *)(GPIOD_BASE_ADDR + 0x14)))
// oragnae PD13
// rouge PD14
// PA0
// PA1
int main(void) {

	// RCC 16MHz
	//
	RCC_AHB1ENR |= (1U << 0); // enable GPIOA

	// configuration for GPIOA PIN 1
	// INPUT
	GPIOA_MODER &= ~(1U << 2);
	GPIOA_MODER &= ~(1U << 3);
	// INPUT
	GPIOA_MODER &= ~(1U << 0);
	GPIOA_MODER &= ~(1U << 1);
	// pull down
	GPIOA_PUPDR &= ~(1U << 2);
	GPIOA_PUPDR |= (1U << 3);

	// enable RCC clock for GPIOD
	RCC_AHB1ENR |= (1U << 3);
	// configuration for GPIOD p

	//PIN 14 OUTPUT
	GPIOD_MODER |= (1U << 28);
	GPIOD_MODER &= ~(1U << 29);
	//PIN 13 OUTPUT
	GPIOD_MODER |= (1U << 26);
	GPIOD_MODER &= ~(1U << 27);
	// PUSH PULL PIN 13
	GPIOD_PUPDR &= ~(3U << (26));
	GPIOD_PUPDR &= ~(3U << (27));
	// PUSH PULL PIN 14
	GPIOD_PUPDR &= ~(3U << (28));
	GPIOD_PUPDR &= ~(3U << (29));

	/* Loop forever */
	while (1) {

		// BTN 1
		if ((GPIOA_IDR & (1U << BTN1))) { // RED
			GPIOD_ODR ^= (1U << LED_RED);
		}
		// BTN 2
		if ((GPIOA_IDR & (1U << BTN0))) { // ORANGE
			GPIOD_ODR ^= (1U << LED_ORANGE);

		}
	}
}
